# Generated by Django 6.0.4 on 2026-04-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_code', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('video_file', models.FileField(upload_to='videos/')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='photos/')),
            ],
        ),
    ]
